---
# Example playbook demonstrating creation of multiple DNS records
# This playbook creates multiple records of different types in a zone

- name: Create Multiple DNS Records
  hosts: localhost
  gather_facts: no
  vars:
    ultra_provider:
      username: "{{ lookup('env', 'ULTRADNS_USERNAME') }}"
      password: "{{ lookup('env', 'ULTRADNS_PASSWORD') }}"
      use_test: "{{ lookup('env', 'ULTRADNS_USE_TEST') | default(false) | bool }}"
    zone_name: "example.com."
    records:
      - name: "www"
        type: "A"
        ttl: 300
        rdata:
          - "192.0.2.1"
      - name: "mail"
        type: "MX"
        ttl: 3600
        rdata:
          - "10 mail.example.com."
      - name: "txt"
        type: "TXT"
        ttl: 300
        rdata:
          - "v=spf1 mx -all"

  tasks:
    - name: Create DNS records
      ultradns.ultradns.record:
        zone: "{{ zone_name }}"
        name: "{{ item.name }}"
        type: "{{ item.type }}"
        ttl: "{{ item.ttl }}"
        rdata: "{{ item.rdata }}"
        state: present
        provider: "{{ ultra_provider }}"
      register: record_result
      loop: "{{ records }}"

    - name: Show record creation results
      debug:
        var: record_result 